### ISSUE TITLE
Possible quick fix for CLI number?

### ISSUE THREAD

**Issue by jacksonhuang21** [legiongis/clitoolbox#20]
Hey Adam,
I just noticed that all the problems I've had with the cli toolbox (displaying geodata/creating excel) relate to missing CLI numbers in the gdb when extracted from enterprise. Is there a possible quick fix in python for this? I don't know python, but I'm praying there's a solution. Using an old extracted gdb is causing some major issues with data accuracy and workflow.

Here's an example comparing an old 2016 gdb and a gdb I just extracted.

(2016)
Executing: DisplayGeodatabase "C:\CLI_GIS\2016 gdb\EntMWR_Spatial_Sep01_1251.gdb" 500391 Layers true false # # true # # # # # # #
Start Time: Thu Dec 28 10:56:32 2017
Running script DisplayGeodatabase...
landscape list is sorted

symbolizing layers by feature class...
original query: ("CLI_NUM" = '500391')
crsite_ln:  ...no records
crsite_pt:  3 features added to display
crsite_py:  1 feature added to display
crothr_ln:  3 features added to display
crothr_pt:  3 features added to display
crothr_py:  11 features added to display
crbldg_pt:  1 feature added to display
crbldg_py:  5 features added to display
crobj_ln:   ...no records
crobj_pt:   17 features added to display
crobj_py:   ...no records
crstru_ln:  6 features added to display
crstru_pt:  ...no records
crstru_py:  ...no records
crdist_py:  1 feature added to display
Completed script DisplayGeodatabase...
Succeeded at Thu Dec 28 10:56:35 2017 (Elapsed Time: 2.57 seconds)

(Recently extracted GDB)
Executing: DisplayGeodatabase "C:\CLI_GIS\2017 gdb\EntMWR_Spatial_Dec28_0954.gdb" 500391 Layers true # # # true # # # # # # #
Start Time: Thu Dec 28 10:57:37 2017
Running script DisplayGeodatabase...
landscape list is sorted

symbolizing layers by feature class...
original query: ("CLI_NUM" = '500391')
crsite_ln:  ...no records
crsite_pt:  ...no records
crsite_py:  ...no records
crothr_ln:  ...no records
crothr_pt:  ...no records
crothr_py:  ...no records
crbldg_pt:  ...no records
crbldg_py:  ...no records
crobj_ln:   ...no records
crobj_pt:   ...no records
crobj_py:   ...no records
crstru_ln:  ...no records
crstru_pt:  ...no records
crstru_py:  ...no records
crdist_py:  ...no records
Completed script DisplayGeodatabase...
Succeeded at Thu Dec 28 10:57:39 2017 (Elapsed Time: 2.25 seconds)

**Comment by mradamcox** [comment]
@jacksonhuang21 this is probably part of a larger issue, because an extracted gdb should come along with the CLI_NUM info, but it seems not to. I'm testing some of those extract tools with Tim right now, so maybe I can include you in the testing. I'll get in touch soon. Thanks.

**Comment by jacksonhuang21** [comment]
@mradamcox I would love to be included in the testing. The limited training I received for updating CLIs in CR GIS relied heavily on the toolbox working as advertised. Which makes sense seeing how the tool is so intuitive and crafted to serve multiple functions for different positions. I will say that going through all the readme docs and guides has been extremely helpful in understanding how the toolbox works behind the scenes. I really appreciate the effort you took in documenting it and creating guides. Any idea on when and why the toolbox started to act up? And is there rough time frame on when v1.2 will be ready?

**Comment by mradamcox** [comment]
@jacksonhuang21 I'm actually a bit amazed at how much documentation I originally wrote, glad you have found it helpful. We are in the process of moving that documentation online (https://github.com/legiongis/clitoolbox/tree/master/docs) and you can view it live (in progress right now though) at http://cli-toolbox.readthedocs.io/en/latest/home.html. After it's been fully migrated, I will go over it and update for 1.2. Read the Docs is great because you can also download pdfs from there (lower left corner). If you or anyone you know would like to contribute to the documentation (with your own experience/guides) please get in touch by e-mail or open an issue here describing what you would like to add.
As for a time frame, I have created a couple of milestones here on github https://github.com/legiongis/clitoolbox/milestones, though as you can see I'm past due on them. I'm plugging away at this, and hopefully I can update those milestones with more realistic dates soon, so check back later.

Regarding testing, I'll send you an e-mail soon.

Finally, as a workaround for the issue at hand, does running the Update Fields in Selected Records with the "Get CLI Info from Table?" box checked help? Make sure to select all of the features in all of the feature classes first. If there was a specific point in time that the IRMA toolbox stopped working properly, that would most likely be due to a change in the CR GIS enterprise tables. We would have to talk with Matt Stutts to learn more about that.

**Comment by jacksonhuang21** [comment]
@mradamcox Thx for the update fields tip, it didn't work unfortunately. Tim suggested that I try an older vers of arcmap. Which in hindsight, should have been done as one of my first attempts at a solution.

**Comment by jacksonhuang21** [comment]
Issue resolved.
